application: blueberry-api
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

# Static
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /bootstrap
  static_dir: static/bootstrap
- url: /images
  static_dir: static/images
- url: /base_files
  static_dir: base_files

# Scripts
- url: /display
  script: display.application
- url: /browse
  script: display.application
- url: /publish_configurations
  script: display.application
- url: /fetch_configurations
  script: display.application
- url: /Data.*
  script: apis.app
- url: /Scalar.*
  script: apis.app
- url: /List.*
  script: apis.app
- url: /Dictionary.*
  script: apis.app
- url: /Table.*
  script: apis.app

libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: latest