application: blueberry-api
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

# Static
- url: /static
  static_dir: static

# Scripts
- url: /display
  script: display.application
- url: /browse
  script: display.application
- url: /publish_configurations
  script: display.application
- url: /fetch_configurations
  script: display.application
- url: /Data.*
  script: apis.app
- url: /Scalar.*
  script: apis.app
- url: /List.*
  script: apis.app
- url: /Dictionary.*
  script: apis.app
- url: /Table.*
  script: apis.app
- url: /login
  script: users.app
- url: /logout
  script: users.app
- url: /register
  script: users.app

- url: /Sorting.*
  script: micro_services.app


libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: webapp2
  version: latest