application: blueberry-api
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

# Static
- url: /static
  static_dir: static

# Scripts
- url: /
  script: display.application
- url: /display
  script: display.application
- url: /browse
  script: display.application
- url: /publish_configurations
  script: display.application
- url: /fetch_configurations
  script: display.application
- url: /add-in_configurations
  script: display.application
- url: /pipelines
  script: display.application
- url: /add-in/add_favorite
  script: add-in.application
- url: /add-in/remove_favorite
  script: add-in.application
- url: /Data.*
  script: apis.app
- url: /Scalar.*
  script: apis.app
- url: /List.*
  script: apis.app
- url: /Dictionary.*
  script: apis.app
- url: /Table.*
  script: apis.app
- url: /FavoriteID.*
  script: apis.app
- url: /login
  script: users.app
- url: /logout
  script: users.app
- url: /register
  script: users.app
- url: /authenticate
  script: users.app
- url: /pipelines.*
  script: pipeline.application
- url: /Sorting.*
  script: micro_services.app
- url: /MicroService/SelectColumns.*
  script: micro_services.app
- url: /proxy/select_headers
  script: proxy.application

- url: /google04255ab34ea37a58.html
  script: display.application


libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: webapp2
  version: latest
- name: numpy
  version: latest